import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./static/Header";
import StoreProvider from "./global/storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
        <html lang="en">
      <body className={inter.className}>
       <div className="flex justify-center items-center flex-col">
       <Header/>
       <div className="w-[95%] min-h-[500px] mt-5 border rounded-md  p-6 flex justify-center items-center md:justify-start">{children}</div>
       </div>
      </body>
    </html>
    </StoreProvider>
  );
}
